### ISSUE TITLE
Dependency on crosstalk

### ISSUE THREAD

**Issue by PhDyellow** [iobis/robis#28] opened 2017-03-09 00:56 UTC
From Rstudio, with both R-3.3.2 and R-3.3.3 I called

```
install.packages("devtools")
devtools::install_github("iobis/robis")
```

But it failed on 

```
 devtools::install_github("iobis/robis")
```

with the message 

```
* installing *source* package 'robis' ...
** R
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'crosstalk'
ERROR: lazy loading failed for package 'robis'
```

Calling the following worked for me. 

```
install.packages("crosstalk")
install.packages("devtools")
devtools::install_github("iobis/robis")
```

Perhaps an update to the docs?

**Comment by pieterprovoost** [comment] 2017-10-16 12:29
Duplicate of https://github.com/iobis/robis/issues/29

**Closed by pieterprovoost** 2017-10-16 12:29 UTC

**Comment by Alex-Shayo** [comment] 2023-10-31 20:53
Thank you. The latter calling worked for me as well.
